# Generated by Django 3.2 on 2025-03-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_student_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_feedback',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='student_feedback',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
