# Generated by Django 3.2 on 2025-03-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20250310_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student_feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
